### Create User

POST http://localhost:3333/api/register
Content-Type: application/json

{
  "name": "User RestAPI",
  "email": "restapi1@email.com",
  "password": "senha123"
}

### Login

POST http://localhost:3333/api/login
Content-Type: application/json

{
  "email": "restapi1@email.com",
  "password": "senha123"
}