### Create User

POST http://localhost:3333/api/register
Content-Type: application/json

{
  "name": "User RestAPI",
  "email": "restapi1@email.com",
  "password": "senha123"
}

### Login User

POST http://localhost:3333/api/login
Content-Type: application/json

{
  "email": "user@email.com",
  "password": "password123"
}

### Login Admin

POST http://localhost:3333/api/login
Content-Type: application/json

{
  "email": "admin@email.com",
  "password": "admin123"
}